# This is a basic workflow that is manually triggered

name: spec-versioning

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - master
    types:
      - closed
concurrency:
  group: spec-verisioning

jobs:
  # This workflow contains a single job called "greet"
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout-repo
        id: checkout-master
        uses: actions/checkout@v2
        with:
          repository: vivian-fan/api-spec-versioning
          token: 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
      - name: install-python
        id: install-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install-py-lib
        id: install-py-lib  
        run: |
          chmod +x ./.github/intall-py-dependecies.sh
          ./.github/intall-py-dependecies.sh
      - name: run-python-script
        id: run-python-script
        run: python bump-version.py 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
